### ISSUE TITLE
Avalex

### ISSUE THREAD

**Issue by eavanvalkenburg** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#14]
Hoi, wat een top sensor! Avalex (https://www.avalex.nl/kalender) zit niet op die twee sites, maar heeft wel zelf een kalender, ook als ical link (https://www.avalex.nl/afvalkalender-uitlegpagina/), is het lastig om dat te integreren?

**Comment by xirixiz** [comment]
Hoi, dat ligt eraan wat de structuur is. Heb je een postcode en huisnummer ergens uit het gebied waar ik mee kan testen?

**Comment by eavanvalkenburg** [comment]
de mijne: 2245AE nummer 20

**Comment by xirixiz** [comment]
Waarom moeilijk doen wanneer het er al is: https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer 😄

**Comment by eavanvalkenburg** [comment]
Goeie, bedankt!

**Comment by IIIdefconIII** [comment]
Niet zo heel handig dit soort info te posten Paardensportvereniging
Koningin Emma haha lama

**Comment by xirixiz** [comment]
Achja, mensen doen er ook een beetje paranoide over tegenwoordig. Wanneer je een beetje handig bent met zoeken kan je van de meeste onder ons wel alle NAW gegevens achterhalen.
