### ISSUE TITLE
Add support for https://www.ophaalkalender.be/

### ISSUE THREAD

**Issue by elRadix** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#17]
Can you add support for https://www.ophaalkalender.be/
![image](https://user-images.githubusercontent.com/6258894/60774280-550e6200-a112-11e9-852f-6773ac1df480.png)

**Comment by aaamoeder** [comment]
^^^^^ this please !!!

**Comment by xirixiz** [comment]
Could do, but it's a totally different format for collecting data. As I have a private matter, I can't spend any time on implementing this. However there's some other Dutch guy (https://github.com/pippyn/), which might be suitable for ophaalkalender.be. Or someone could ofcourse create a pull request :).
