### ISSUE TITLE
Error while setting up platform afvalwijzer

### ISSUE THREAD

**Issue by passie** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#18]
When I add the following either via HACS or manual via custom_components folder to configuration.yaml

>   - platform: afvalwijzer
    url: 'mijnafvalwijzer.nl'
    postcode: '$postcode'
    huisnummer: '$number'
    toevoeging: ''
    label_geen: 'Geen'

I'm getting the bellow error message

`
Error while setting up platform afvalwijzer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 84, in setup_platform
    json_obj = response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

Any advise on what i'm doing wrong?
Is this because my township isn't supported in some way?

--- Passie

**Comment by Diondk** [comment]
My configuration looks like this. 

`- platform: afvalwijzer
  url: 'mijnafvalwijzer.nl'
  postcode: !secret postcode
  huisnummer: !secret huisnummer
  label_geen: 'Geen'`

where the secrets for the postalcode and number is the postal code and the number without the ''

**Comment by xirixiz** [comment]
It seems to have something todo with mijnafvalwijzer.nl not providing any data. Can you try entering the following url, with your postal code and housenumber?

```https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode={1}&street=&huisnummer={2}&platform=phone&langs=nl&```

**Comment by passie** [comment]
> It seems to have something todo with mijnafvalwijzer.nl not providing any data. Can you try entering the following url, with your postal code `{1}` and housenumber `{2}`?
> 
> `https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode={1}&street=&huisnummer={2}&platform=phone&langs=nl&`

When using the url you provided with altered postal code and house number it's giving me back data in the form of json.
Though when installing the plugin via hacs and adding the following config to my configuration.yaml i'm still getting the above error message

```
  - platform: afvalwijzer
    url: 'mijnafvalwijzer.nl'
    postcode: '2131AN'
    huisnummer: '13'
    label_geen: 'Geen'
```
Any idea what's wrong?

**Comment by Diondk** [comment]
When i fill in your data on the website of afvalwijzer, i am getting an error: Uw adres is niet bekend bij ons. Neem contact op met uw gemeente

probably your city isnt providing the data to afvalwijzer.

**Comment by passie** [comment]
In that case i’ll close the issue. Thanks for the support
