### ISSUE TITLE
Exclude trash types

### ISSUE THREAD

**Issue by fsaris** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#20]
I have a lot of trash sensors/options that are not interesting for me (my family). Would be cool if it was possible to exclude these types from the today/tomorrow checks.

Would it be possible to add a config option to list types to exclude?

For me it would also be okay to fully exclude them. So also don't add them as sensor at all.

Would you be open for such a feature?

**Comment by xirixiz** [comment]
Hi fsaris,

That would be a nice feature indeed, and I think it should be possible to add it easily. I'll look into it soon.

**Comment by xirixiz** [comment]
To hard to realize unfortunately, closing the issue.
