### ISSUE TITLE
Using the API

### ISSUE THREAD

**Issue by barrystaes** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#21]
This sensor apparently (have not used it yet) successfully scrapes the webpage which i find impressive with the unfriendly structure, date formats, and pretty incomplete overview.  👌 

Looking around for a nice data format a while ago, i noticed the Android app uses a JSON API:

```
Request:
GET https://api.afvalstoffendienstkalender.nl/ 

Response:
{
  "response":"NOK",
  "data":[],
  "error":"Not valid input"
}
```
So that's not an actual request the app does, i need to look into that when i find the time.

The webpage also uses something similar at the "enter address" dialog, before returning the page this sensor usually scrapes:

```
Request:
GET https://oisterwijk.afvalstoffendienstkalender.nl/site/postcodeinfo?LoginForm%5Bpostcode%5D=&postcode=5061DR&LoginForm%5Bhuisnummer%5D=&huisnummer=120&LoginForm%5Btoevoeging%5D=&toevoeging=&method=getPostcodeInfo
(and some headers)

Response:
{
  "response": "OK",
  "address": "Oisterwijk, Langvennen-oost 120 ",
  "data": "5.1792085289232,51.5846422027994",
  "street": "Langvennen-Oost"
}
```

### Todo:
- test the App and document API here.

**Comment by xirixiz** [comment]
Hi Barrystaes, 

Thanks for sharing, but could you please add some additional info what you're trying to achieve?

The sensor I created uses the json api and it isn't scraping the website. I created a scraper a while ago, but that was a big mistake 😄

**Comment by barrystaes** [comment]
My bad - now closing this issue because API is already used.  
I apparently read dated forum posts mentioning a scraper.

Thanks for developing this component!  
I installed your component yesterday via HACS (didnt know about that either) and its working great out of the box. 

PS. a suggestion: if there is a good default or defacto lovelace card for this, it might be worth mentioning in the repo readme to help noobs like me on the right track.
