### ISSUE TITLE
Lovelace

### ISSUE THREAD

**Issue by jgelon** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#22]
Hi Xirixiz

I love your sensor for Home Assistant and I installed it via Hacs. However I can't find the code you used for that Lovelace layout (the one in the readme).
Could you share that aswell?

**Comment by xirixiz** [comment]
Hi Jgelon,

Sure, here you go: https://github.com/xirixiz/home-assistant

**Comment by barrystaes** [comment]
This would make a nice example config in the readme.md

**Comment by xirixiz** [comment]
done barrystaes, good point!
