### ISSUE TITLE
Platform not found: sensor.afvalwijzer

### ISSUE THREAD

**Issue by P-Verbrugge** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#23]
I just ran a config_check for my configuration against Hass 0.97. I run version 0.96.5 now.

The config check fails for version 0.97. I get the following error:
`
Failed config
  General Errors: 
    - Platform not found: sensor.afvalwijzer
`
I run afvalwijzer verion 3.0.9.

**Comment by xirixiz** [comment]
Hi P-Verbrugge, did you manage to fix this? I have no other complaints the component isn't working, otherwise you should set the logging to debug and share your logfiles.

**Comment by Smiggel** [comment]
The app that checks the config, says the afvalwijzer could not be found. But when I update the system, it still works. Doesn’t seem to be a real problem.

**Comment by P-Verbrugge** [comment]
The app that checks the config, says the afvalwijzer could not be found. But when I update the system, it still works. Doesn’t seem to be a real problem.

**Comment by KnightsKingdom** [comment]
Experiencing the same issue as P-Verbrugge. After installing afvalwijzer v3.0.9 via HACS and setting up the sensor info the same config error shows up after config validation. HASS wont even let me restart because of the error. 
So no real debug info is available...
HASS version 0.97.2

**Comment by xirixiz** [comment]
Ofcourse you can, for example like this :):

`
logger:
  default: warn
  logs:
    #homeassistant.components.device_tracker: critical
    custom_components.sensor.mijnafvalwijzer: debug
`

**Comment by KnightsKingdom** [comment]
Thanks for the help, I added above to the logger component but it doesn't help much.
In dev-info the only entry I get is:

Thu Aug 29 2019 20:39:22 GMT+0200 (Midden-Europese zomertijd)
Platform not found: sensor.afvalwijzer

and below one, but I get those for every HACS install

Thu Aug 29 2019 20:39:16 GMT+0200 (Midden-Europese zomertijd)
You are using a custom integration for afvalwijzer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

The home-assistant.log in the config directory is empty, is there another logfile I can check?

btw there is no sensor created for mijnafvalwijzer, so probably custom_components.sensor.mijnafvalwijzer: debug doesn't give any output.

**Comment by P-Verbrugge** [comment]
I did the config check today for Hassio 0.98 and got this error this time:   General Errors: 
    - Platform error sensor.afvalwijzer - No module named 'bs4'

I have not yet upgraded Hassio. I will do this tomorrow.

**Comment by KnightsKingdom** [comment]
I checked the files and bs4 stands for beautifulsoup4, it's a python library that I didn't had. Installed it in my venv and now the config error is gone.

But still no new sensors are created.

**Comment by KnightsKingdom** [comment]
Update: just found out I get no data because my postalcode isn't on afvalwijzer.

Hope you can get it working @P-Verbrugge

**Comment by xirixiz** [comment]
> I did the config check today for Hassio 0.98 and got this error this time: General Errors:
> - Platform error sensor.afvalwijzer - No module named 'bs4'
> 
> I have not yet upgraded Hassio. I will do this tomorrow.

@P-Verbrugge you need to install bs4 in hassio: pip install beautifulsoup4

**Comment by P-Verbrugge** [comment]
I tried pip install beautifulsoup4, but it can’t find the command pip. I had to use pip3. 

After installing beautifulsoup4, and checking the config, I still get the error that bs4 is not found.

**Comment by xirixiz** [comment]
Ok, then you should find out how bs4 can be installed, maybe @KnightsKingdom can help you out with hassio. I`m using HASS in Docker and there bs4 is already available.

**Comment by KnightsKingdom** [comment]
@P-Verbrugge I install both beautifulsoup4 and bs4, although they appear to be the same, bs4 installed different packages. pip3 install bs4 should work. I also restarted my complete system, but don't know if that's really necessary for HA to import the new library.

**Comment by P-Verbrugge** [comment]
@KnightsKingdom  Hmmm, no luck. When checking the config it still says it's missing bs4

**Comment by xirixiz** [comment]
Hi P-Verbrugge, it seems something is setup differently with your Python environment. Do you use a virtualenv?

https://www.home-assistant.io/docs/installation/virtualenv/

**Comment by P-Verbrugge** [comment]
@xirixiz I use a default Hass.io image that I put on a SD card. Don't have anything special.

**Comment by xirixiz** [comment]
@P-Verbrugge this isn't related to the component, but really environment (Python) related. I think it's better to ask this on the community forum. I`m reading that more people have issues installing Python libraries in hass.io. Good luck! I'll close this issue now as it isn't component related.
