### ISSUE TITLE
Error while setting up platform afvalwijzer Traceback

### ISSUE THREAD

**Issue by GitHubxtsnl** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#25]
Hi,

running this one on a RBPi3+ with Home Assistant 0.101.3 and I'm getting the following error in the logs:

any tips or ideas?

`Log Details (ERROR)
Tue Nov 19 2019 11:25:38 GMT+0100 (Central European Standard Time)
Error while setting up platform afvalwijzer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 85, in setup_platform
    json_obj = response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by xirixiz** [comment]
Hi,

It looks like no data is retrieved from mijnafvalwijzer. Can you try the following (replace postcode and huisnummer):

```
https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=<POSTCODE>&street=&huisnummer=<HUISNUMMER>&lang=nl
```

**Comment by GitHubxtsnl** [comment]
Hi, thanks for the quick reply. I tried the link, replaced the postcode and huisnummer and I get a **NOK** back.

**Comment by advead** [comment]
hello can somebody tell my whats wrong with this tekxt in my configuration.yaml

sensor:
   - platform: afvalwijzer
     url:  mijnafvalwijzer.nl
     postcode: 1234AA
     huisnummer: 122
     toevoeging: ''
     label_geen: 'geen'

I have the error:

Invalid config for [sensor.afvalwijzer]: [url] is an invalid option for [sensor.afvalwijzer]. Check: sensor.afvalwijzer->url. (See C:\Users\mypc\AppData\Roaming\.homeassistant\configuration.yaml, line 19). Please check the docs at https://home-assistant.io/integrations/afvalwijzer/

line 19 starts with  sensor:

**Comment by xirixiz** [comment]
Please use code quote: https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax

Example config:  https://github.com/xirixiz/home-assistant/blob/master/packages/trash.yaml

Remove the config items you’re not using and make sure the yaml is aligned correctly.
