### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by glegierse** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#26]
Trying to get the afvalwijzer component to run (running HASSIO on a DS218+ Synology NAS as a package/docker) results in the following error and prevents hassio from restarting after 
 adding the sensor to configuration.yaml: 

ERROR (SyncWorker_0) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/afvalwijzer/manifest.json: Expecting value: line 7 column 1 (char 6)

Hassio is exposed through the built in synology nginx proxy (with websockets).

**Comment by glegierse** [comment]
Solved, seems like windows messed up the files when downloaded separately instead of zipped. After zipped download and transferred/unpacked in correct folder on the NAS everything works!

**Comment by xirixiz** [comment]
Soon release 4.0.0 will be released. It's a major improvement and also I`m adding it as a integrated component for HASS.
