### ISSUE TITLE
platform: time => time_pattern

### ISSUE THREAD

**Issue by svanzon** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#32]
I am using your script thru HACP. I am new to HA, but when I imported the automation.yaml I got an error.

After some searching I found out that:

> Any automation that uses “hours” “minutes” or “seconds” in the trigger should now be “time_pattern” instead of just “time” … it was a breaking change a few versions ago.
> 
> Automations that use “00:00:00” are still just “time”
Source: [https://community.home-assistant.io/t/minutes-is-an-invalid-option-for-error/103172](url)

Maybe you can change.

**Comment by xirixiz** [comment]
Fixed! Thanks!
