### ISSUE TITLE
error

### ISSUE THREAD

**Issue by janwbro** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#33]
Hi
I get an error with aoutmation

Invalid config for [automation]: [trigger] is an invalid option for [automation]. Check: automation->action->1->trigger. (See /config/configuration.yaml, line 179).

**Comment by xirixiz** [comment]
Hi, it means your automation config isn't correctly configured. It isn't related to the custom_component.

**Comment by janwbro** [comment]
ok
i used the automation config https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer
that working correct only the automation

**Comment by xirixiz** [comment]
You probably use the automation.yaml file and aren't working with packages? In that case, don't put the automation: in front and align the rest of the code properly.

**Comment by xirixiz** [comment]
Another tip. Next time when you log an issue, add a proper description/title ;). Error is rather generic.

**Comment by janwbro** [comment]
Ok sorry
 tnx
