### ISSUE TITLE
Sensor grammer error: sensor.trash_firs_waste_type or sensor.trash_first_waste_type

### ISSUE THREAD

**Issue by P-Verbrugge** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#36]
After updating to the latest version I noticed a grammer error: It says firs_waste instead of first_waste. This breaks the sensor that used to work in 4.0.1.

**Comment by xirixiz** [comment]
Hi, there shouldn't be a sensor called like that at all :)

These 3 sensors should appear using version 4.1.0.
sensor.trash_firs_next_item
sensor.trash_first_next_date
sensor.trash_first_next_in_days

**Comment by Mariusthvdb** [comment]
You’re missing a t on the trash_firsT_next_item is what OP means?

**Comment by P-Verbrugge** [comment]
@Mariusthvdb you are correct. The t is missing in the sensor name.

**Comment by xirixiz** [comment]
Fixed in release 4.1.1
