### ISSUE TITLE
custom card horizontal en vertical stack

### ISSUE THREAD

**Issue by janwbro** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#38]
Who do I know I will get this done
I want to make rows
among each other
I know it has something to do with horizontal stack but I can't
next to each other it works but rows below that I can't manage

cards:
  - entity: script.zachter_radio
    icon: 'mdi:volume-minus'
    size: 35px
    style:
      - color: var(--sidebar-selected-icon-color)
    type: 'custom:button-card'
  - entity: script.mute_radio
    icon: 'mdi:volume-off'
    size: 35px
    style:
      - color: var(--sidebar-selected-icon-color)
    type: 'custom:button-card'
  - entity: script.harder_radio
    icon: 'mdi:volume-plus'
    size: 35px
    style:
      - color: var(--sidebar-selected-icon-color)
    type: 'custom:button-card'
  - entity: script.stop_radio
    icon: 'mdi:stop'
    size: 35px
    style:
      - color: var(--sidebar-selected-icon-color)
    type: 'custom:button-card'
type: horizontal-stack

**Comment by janwbro** [comment]
I already have it

**Comment by Frankster-NL** [comment]
Can you share your solution?

**Comment by janwbro** [comment]
title: Radio luisteren
views:
  - title: Header
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: script.play_rautemusik_main
        icon: 'mdi:radio-tower'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        name: Radio 2
      - type: 'custom:button-card'
        entity: script.play_rautemusik_rock
        icon: 'mdi:radio-tower'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        name: Q-music
      - type: 'custom:button-card'
        entity: script.play_rautemusik_main
        icon: 'mdi:radio-tower'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        name: Komt og
      - type: 'custom:button-card'
        entity: script.playgrunfm
        icon: 'mdi:radio-tower'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        name: Grunn.FM
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: script.noord
        icon: 'mdi:radio-tower'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        name: RTV Noord
      - type: 'custom:button-card'
        entity: script.radiocontinu
        icon: 'mdi:radio-tower'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        name: Continu
      - type: 'custom:button-card'
        entity: script.sterrennl
        icon: 'mdi:radio-tower'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        name: Sterren.nl
      - type: 'custom:button-card'
        entity: script.nonstopvijfdrieacht
        icon: 'mdi:radio-tower'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        name: Radio 538
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        entity: script.zachter_radio
        icon: 'mdi:volume-minus'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
      - type: 'custom:button-card'
        entity: script.mute_radio
        icon: 'mdi:volume-off'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
      - type: 'custom:button-card'
        entity: script.harder_radio
        icon: 'mdi:volume-plus'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
      - type: 'custom:button-card'
        entity: script.stop_radio
        icon: 'mdi:stop'
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
