### ISSUE TITLE
picture in the custom button cart

### ISSUE THREAD

**Issue by janwbro** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#39]
who knows how to add my own picture in the custom button cart

     - entity: script.play_radio2
        entity_picture:  local/radio2.jpg
        size: 35px
        style:
          - color: var(--sidebar-selected-icon-color)
        type: 'custom:button-card'

but this works fine

![rad2](https://user-images.githubusercontent.com/59759210/73836539-caa8f080-480f-11ea-8c11-47399f45bdbd.PNG)

**Comment by Mariusthvdb** [comment]
How is this related to AfvalWijzer ?

**Comment by janwbro** [comment]
nothing

**Comment by Mariusthvdb** [comment]
You’d best take it to the community then and close this here.

**Comment by janwbro** [comment]
ok tnx
