### ISSUE TITLE
Instructions for lovelace (icons etc).

### ISSUE THREAD

**Issue by remyderuysscher** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#41]
I'm missing instructions for creating a nice Lovelace sensor for this component. Just like the picture shows.

**Comment by xirixiz** [comment]
Lovelace configuration is pretty personal. You can browse my hass config as an example, and you may find some useful information within the lovelace documentation. Good luck!

**Comment by riemers** [comment]
Your hass config does not include a lovelace config. I think a lot of people would find it helpfull (even when its personal preference)
