### ISSUE TITLE
newest afvalwijzer increases HA response time by 1000ms

### ISSUE THREAD

**Issue by jelmerkk** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#44]
Hey guys,
Since the last time I upgraded the afvalwijzer plugin, my HA response time went through the roof. Using different snapshots and monitoring my HA ping/response time I was able to narrow it down to the afvalwijzer plugin, installed on 105.3 and with the latest HACS .
This is the config I use:
`platform: afvalwijzer
zipcode: !secret postcode
housenumber: !secret huisnummer`

**Comment by xirixiz** [comment]
Please try version 4.1.4 (just released)

**Comment by jelmerkk** [comment]
Seems to have fixed it, thanks!
