### ISSUE TITLE
sensor.trash_first_next_item showing wrong input

### ISSUE THREAD

**Issue by avehome** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#46]
Hi,

I think trash_first_next_item should never be the same as trash_today.
Like trash_first_next_in_days never showing 0 days.
In example below sensor.trash_first_next_item should be gft

![image](https://user-images.githubusercontent.com/50752001/74285133-7b8a2080-4d25-11ea-93a6-9df0295c3567.png)

**Comment by xirixiz** [comment]
Goed punt! Some people like to have it as you stated, others don't. So I guess the best thing for me todo is to check wether it's possible to convert this to a configuration item / option. I`ll check it Tomorrow.

**Comment by xirixiz** [comment]
I`m able to fix this, this option will be added to release 4.1.5

**Comment by avehome** [comment]
Thank you so much! It's working perfect now 👍
