### ISSUE TITLE
Instructies gevolgd maar krijg foutmelding.

### ISSUE THREAD

**Issue by YRRK** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#49]
Hi! Ik wilde de handige afvalwijzer proberen dus:

In custom_components/afvalwijzer de 3 bestanden toegevoegd:
__init__.py
manifest.json
sensor.py

In de bekende config.yaml
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    zipcode: 3512 WB
    housenumber: 15
    count_today: true
    default_label: Geen

Reboot gedaan.
Krijg ik de foutmelding:

Platform error sensor.afvalwijzer - No module named 'Afvaldienst'

Heb je enig idee wat ik verkeerd heb gedaan? :-)
Ik draai een standaard Hass.io installatie 32bit Pi4b 105.4

**Comment by xirixiz** [comment]
Gebruik je hass.io wellicht? Het ziet ernaar uit dat de python library afvaldienst niet geïmporteerd kan worden. Komt daar geen melding van voorbij in de logfiles?

**Comment by YRRK** [comment]
Ja ik gebruik de officiele config https://www.home-assistant.io/hassio/installation/

**Comment by riemers** [comment]
Probeer [HACS](https://github.com/hacs/integration) te installeren, heb je gelijk nog meer toegevoegde waarde. Daar kan je ook makkelijke deze integratie mee installeren.

**Comment by YRRK** [comment]
> Gebruik je hass.io wellicht? Het ziet ernaar uit dat de python library afvaldienst niet geïmporteerd kan worden. Komt daar geen melding van voorbij in de logfiles?

Hmm nee geen foutmelding daarvan in de logfile.

**Comment by YRRK** [comment]
> Probeer [HACS](https://github.com/hacs/integration) te installeren, heb je gelijk nog meer toegevoegde waarde. Daar kan je ook makkelijke deze integratie mee installeren.

Heb hem nogmaals geherinstalleerd nu via HACS. Weer foutmelding: Platform error sensor.afvalwijzer - No module named 'Afvaldienst'

**Comment by riemers** [comment]
```
sensor:
  - platform: afvalwijzer
```
Wellicht ter overvloed, wel sensor ervoor? Tenminste zo heb ik hem in mijn config ;)

**Comment by YRRK** [comment]
Ja, hij staat tussen de sensors, dus ja.

> Op 16 feb. 2020 om 22:01 heeft Erik-jan Riemers <notifications@github.com> het volgende geschreven:
> 

﻿
sensor:
  - platform: afvalwijzer
Wellicht ter overvloed, wel sensor ervoor? Tenminste zo heb ik hem in mijn config ;)

**Comment by riemers** [comment]
ik zie bij jou 1 spatie voor de "- platform" normaliter zijn dat er 2.. maar kan ook aan github liggen.

**Comment by YRRK** [comment]
Ja dat is github, dan had ik het even netjes als code moeten copy pasten. Maar ik gebruik de officiële Addon config editor van HomeAssistant.io Die geeft een warning wanneer je iets verkeerd in de config zet of spaties vergeet. Zelfs de reboot zou niet lukken als sensor er niet voor staat. Dus dat deel is gecoverd. :)

> Op 16 feb. 2020 om 22:23 heeft Erik-jan Riemers <notifications@github.com> het volgende geschreven:
> 

﻿
ik zie bij jou 1 spatie voor de "- platform" normaliter zijn dat er 2.. maar kan ook aan github liggen.

**Comment by riemers** [comment]
Enige verschil is dat ik op intel draai en jij op arm. Heb iig allemaal sensor.trash* dingen. Je kan nog kijken of je fysiek de bestanden ziet staan. Neem aan dat de logs niet veel vertellen in developer tools.

**Comment by xirixiz** [comment]
Het probleem is zoals ik eerder aangaf, hass.io installeert kennelijk de required library niet. Aan de configuratie ligt het niet, anders zou je die melding niet krijgen dat hass.io de Pyhton library afvaldienst niet kan vinden: https://pypi.org/project/afvaldienst/

Wat je kan proberen is sensor.py uit te breiden met:
```
REQUIREMENTS = ['afvaldienst==0.6.5']
```
Wellicht dat hass.io de library dan wel download....

Verder zou je in kunnen loggen op de Docker container en het onderstaande kunnen uitvoeren om te testen of het dan wel werkt (daarna hass in de container herstarten, dus niet een nieuwe container starten).
```
pip install 'afvaldienst==0.6.5'
```
Logging al in debug mode gezet?
https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer

**Comment by YRRK** [comment]
> Het probleem is zoals ik eerder aangaf, hass.io installeert kennelijk de required library niet. Aan de configuratie ligt het niet, anders zou je die melding niet krijgen dat hass.io de Pyhton library afvaldienst niet kan vinden: https://pypi.org/project/afvaldienst/
> 
> Wat je kan proberen is sensor.py uit te breiden met:
> 
> ```
> REQUIREMENTS = ['afvaldienst==0.6.5']
> ```
> 
> Wellicht dat hass.io de library dan wel download....
> 
> Verder zou je in kunnen loggen op de Docker container en het onderstaande kunnen uitvoeren om te testen of het dan wel werkt (daarna hass in de container herstarten, dus niet een nieuwe container starten).
> 
> ```
> pip install 'afvaldienst==0.6.5'
> ```
> 
> Logging al in debug mode gezet?
> https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer

Hmm dit gaat boven mijn met. Ik wilde afhaken, maar besloot hem nog een keer te installeren.

`sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    zipcode: 3512WB
    housenumber: 15
    suffix:
    count_today: true
    default_label: Geen
`
Nu krijg ik een andere foutmelding (dus hij lijkt nu wel te laden):

2020-02-17 19:50:00 ERROR (MainThread) [homeassistant.components.hassio] Invalid config for [sensor.afvalwijzer]: string value is None for dictionary value @ data['suffix']. Got None. (See ?, line ?).

**Comment by xirixiz** [comment]
```
platform: afvalwijzer
provider: mijnafvalwijzer
zipcode: 3512WB
housenumber: 15
```

Gebruik alleen de waarden die je nodig hebt en probeer het dan nog eens. Je geeft nu een key (suffix) op, maar geen value (A, B, oid) mee.

**Comment by YRRK** [comment]
Oh dat was me niet duidelijk dat ik die dan weg moest laten. Oke 3x is scheepsrecht. Hij doet 't!

**Comment by Mariusthvdb** [comment]
> Het probleem is zoals ik eerder aangaf, hass.io installeert kennelijk de required library niet. 

voor de referentie: Afvalwijzer op Hass.io werkt prima hier, geen enkele reden om te vermoeden dat de library niet wordt geïnstalleerd.

wat bij mij wel voor verwarring had gezorgd, was de voorbeeld configuratie, met enkele waarden die meer een uitleg zijn, dan een feitelijk toegestane waarde.. 

de documentatie zou op dat punt net iets formeler kunnen/moeten zijn. Zo was ik in verwarring door het veld suffix. Ik was in de veronderstelling dat dat een suffix zou zijn die aan de sensor naam zou worden toegevoegd, maar het is een suffix op het adres-veld...

ook wat er staat bij count_today, en default_label is niet echt duidelijk, zeker niet als je dit CC niet eerder gebruikte ..

hoe dan ook, het wekt nu als het moet, dus: thanks! @xirixiz . super.
