### ISSUE TITLE
icons 

### ISSUE THREAD

**Issue by Puch-tdi** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#50]
Hi there, i installed this via HACS, now i have working sensors but only if i add them one by one and only as a text (but with correct dates and kinds of trash)
I like to know how to get nice icons or maybe a card like in the example afvalwijzer_lovelace.png.
I hope someone can help me with this.
Thanks in advance.

Sander

**Comment by xirixiz** [comment]
Hi Sander,

Check my hass config here: https://github.com/xirixiz/my-hass-config

Good luck!
