### ISSUE TITLE
Make afvalwijzer an "official integration"?

### ISSUE THREAD

**Issue by YRRK** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#51]
Dear Xirixiz,

Would it be possible to make Afvalwijzer an "official integration" to work without custom component or HACS? Like the other integrations like https://github.com/timvancann/pyavri ?

:-)

**Comment by xirixiz** [comment]
Hi, did try once....but I had to re-write a lot. However, that has been a while. I`ll try to make it official soon.

**Comment by YRRK** [comment]
Cool, more people can benefit from it, and we can skip loading hacs on the poor Raspberry Pi ;-)

**Comment by YRRK** [comment]
Shall I close the issue? You know the wish is there :-)

**Comment by rodehoed** [comment]
Making it an official integration would be awesome. But of course I do not know the requirements.
