### ISSUE TITLE
GFT contains space, causing day_after_tomorrow to show wrong picture

### ISSUE THREAD

**Issue by tomlevels** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#54]
Due to an extra whitespace in the retrieved data ("gtf " instead of "gft"), my trash_day_after_tomorrow sensors do not display the correct entity_image. I did see this error for previous versions, but those did not have a trash_day_after_tomorrow yet.

**Comment by xirixiz** [comment]
I think I solved it. In the custom component, can you update this file:
```
custom_components/afvalwijzer/manifest.json
```
On line 6 to:
```
"afvaldienst==0.6.7"
```
and restart hass.

**Comment by tomlevels** [comment]
Yes, now it works fine, thanks!
