### ISSUE TITLE
Platform error sensor.afvalwijzer - No module named 'Afvaldienst'

### ISSUE THREAD

**Issue by DaGrooves** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#63]
I have setup everything according to the installation manual.
When i run the 'Check Config' I get the following error:
Platform error sensor.afvalwijzer - No module named 'Afvaldienst'
Any idea what might cause this?

**Comment by etamminga** [comment]
Same here!

**Comment by xirixiz** [comment]
On hassio? Please share some more details about your setup please. 👍🏻

**Comment by etamminga** [comment]
Yes it is hass.io on VMWare from the image provided by home-assistant. I had home assistant installed as a pilot on an old Pi and at that time (late march) the afvalwijzer plugin worked just fine.
On VMWare I just cannot get the plugin working. Working on it right now.

Any other info that would help me/you troubleshooting?

Current config in the sensor: department:
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    zipcode: 5464PV
    housenumber: 49

**Comment by xirixiz** [comment]
https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer/issues/49

**Comment by etamminga** [comment]
Fixed it!

A reboot of the VM fixed my issue. Reloading Hass was not sufficient. Learning here.....
