### ISSUE TITLE
You mind sharing your llcard?

### ISSUE THREAD

**Issue by includes08** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#64]
How did you get it like this?
https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer/raw/master/afvalwijzer_lovelace.png

mind sharing?

**Comment by includes08** [comment]
I've read you used this https://github.com/ciotlosm/custom-lovelace but i love your pictures as well :) might aswell share the whole layout thehe

**Comment by xirixiz** [comment]
Hi, please search the closed issues section. You'll find this:
https://github.com/xirixiz/Home-Assistant-Sensor-Afvalwijzer/issues/50
