### ISSUE TITLE
Installation through hacs brakes HA

### ISSUE THREAD

**Issue by snoekieboe** [xirixiz/Home-Assistant-Sensor-Afvalwijzer#68]
Hi,

When installing the Afvalwijzer addon through HACS it breaks Home Assistant to a point where it will not start anymore and you have to restore a snapshot to get it working again:

**My HA system info:**

chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.8.3
supervisor | 229
timezone | Europe/Amsterdam
version | 0.113.1
virtualenv | false

**Comment by xirixiz** [comment]
Hi, do you have some logfiles with messages why it breaks? I tried to replicate it, but didn't have this issue.

**Comment by Toinieboy** [comment]
I had the same issue here. Integration through HACS went fine! But as soon as you add the code to the configuration, HACS won't load anymore after a reboot

**Comment by jpiscaer** [comment]
Same. Adding the repo via HACS and rebooting is fine. Adding the afvalwijzer platform to configuration.yaml breaks HASS beyond recovery. Remove the code, reboot, and HASS works again.

**Comment by xirixiz** [comment]
I really like to investigate this, but I can't repoduce it somehow. Are you all using an ARM based platform? If I can't repoduce it, maybe you can with a second instance of HASS or something. I ofcourse need some more information in order to be able to solve this. Thanks!

**Comment by jpiscaer** [comment]
It's kinda hard to find logs on the hass.io appliance when it won't boot. I'm running HASS as a VM on x86, latest version.

**Comment by fstelte** [comment]
I would like to add to this issue, that I have had this component a while through HACS, but noticed today that my config was broken.
The error I am getting No JSON data received from https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=XXXX&street=&huisnummer=X&toevoeging=&langs=nl

**Comment by TimSoethout** [comment]
I think I have the same issue: 
```2020-09-10 14:07:42 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up onkyo platform for media_player
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Afvaldienst/Afvaldienst.py", line 51, in __get_data_json
    jsonResponse = requests.get(jsonUrl).json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/afvalwijzer/sensor.py", line 70, in async_setup_platform
    count_today
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/Afvaldienst/Afvaldienst.py", line 43, in __init__
    self._jsonData = self.__get_data_json()
  File "/usr/local/lib/python3.7/site-packages/Afvaldienst/Afvaldienst.py", line 53, in __get_data_json
    raise SystemExit('No JSON data received from ' + jsonUrl)
SystemExit: No JSON data received from https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=XXXXXX&street=&huisnummer=XX&toevoeging=&langs=nl```

Using HACS on HASSIO on Odroid C2 (arm).

**Comment by fstelte** [comment]
Yes I get the same, empty HTTP 200 OK response

**Comment by xirixiz** [comment]
Thanks for the additional info! Do you exacly see the below, or did you remove the values and replaced them with "X"?

```https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=XXXX&street=&huisnummer=X&toevoeging=&langs=nl```

What do you see when you replace the "X" values with the values matching your area code(s) and just enter it in a browser? Can you provide me that?

**Comment by JBS5** [comment]
> Thanks for the additional info! Do you exacly see the below, or did you remove the values and replaced them with "X"?
> 
> `https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=XXXX&street=&huisnummer=X&toevoeging=&langs=nl`
> 
> What do you see when you replace the "X" values with the values matching your area code(s) and just enter it in a browser? Can you provide me that?

I got an empty white page when doing that.

**Comment by lubbertkramer** [comment]
Lots of users report this problem today at [Tweakers](https://gathering.tweakers.net/forum/list_message/63720578#63720578), after a discussion at the official Discord where Afvalwijzer was shown as the error it's removed from HACS

**Comment by xirixiz** [comment]
That's not right. You should see a page full of text and json data... Does mijnafvalwijzer.nl show any data via the UI?

**Comment by JBS5** [comment]
> That's not right. You should see a page full of text and json data... Does mijnafvalwijzer.nl show any data via the UI?

Yes. https://mijnafvalwijzer.nl/nl/XXXX/X/ shows the correct data.

**Comment by xirixiz** [comment]
Ok, seems that mijnafvalwijzer.nl has some issues presenting json data, or mijnafvalwijzer.nl removed the json url. This has nothing to do with the component itself. As it shows, no data is being received from mijnafvalwijzer.nl

**Comment by JBS5** [comment]
> Ok, seems that mijnafvalwijzer.nl has some issues presenting json data, or mijnafvalwijzer.nl removed the json url. This has nothing to do with the component itself. As it shows, no data is being received from mijnafvalwijzer.nl

Kind of tricky as HA will not start (and crash) when this happen. Removing the custom component was required to make HA start again.

**Comment by xirixiz** [comment]
Yes, I fully agree, I need to modify the code a bit for this. I`ll look into it later Today or Tomorrow morning.

**Comment by fstelte** [comment]
That would be great, disabled the component as a workaround for now

**Comment by Guus-H** [comment]
I have a similar issue, but did not need to restore snapshot. 
My HA gets stuck in "Home Assistant is starting, not everything will be available until it is finished." But I'm able to change my config and comment out the Afvalwijzer and restart.

**Comment by xirixiz** [comment]
Ik heb zojuist een nieuwe release uitgebracht, 4.3.2. Het probleem van een HASS lockup zou daarmee verholpen moeten zijn, dat wil niet zeggen dat het nu weer volledig werkt, dat issue ligt zoals eerder genoemd bij mijnafvalwijzer.nl zelf.

**Comment by xirixiz** [comment]
In English. I just released 4.3.2 of this component. This will prevent HASS from locking up, but can't resolve the issue of not retrieving any data from mijnafvalwijzer.nl, that's an issue on their side.

**Comment by xirixiz** [comment]
Verfied, HASS is starting nicely

**Comment by Mariusthvdb** [comment]
just as a possible extra detail: could you push a notification the afvalwijzer server isn't responding properly/not sending data? tight now we have to guess.

maybe set an attribute or a binary_sensor on the connection, and have that use `device_class: problem`. In which case we could create the notification ourselves based on the binary being 'on'.


thanks for the quick fix, indeed confirming HA is starting alright now.

**Comment by xirixiz** [comment]
PR created for HACS as well: https://github.com/hacs/default/pull/611

Thanks @Mariusthvdb, I like your suggestion, I`ll look into it later.

**Comment by Mariusthvdb** [comment]
cool, thanks.

my temporary template is only second best to that, a true 'sensing' binary would be optimal:

```
{% if states.sensor.saver_trash_today is not none %} {{states('sensor.saver_trash_today')}}
{% else %} No response from Saver
{% endif %}
```
;-)

**Comment by MrUserY** [comment]
Hey ik had een reply gedaan op github notifications, maar dat komt nergens aan natuurlijk.
Ik wilde even zeggen dat de afvalwijzer niet meer op HACS te vinden is.

**Comment by JBS5** [comment]
> @xirixiz Hey ik had een reply gedaan op github notifications, maar dat komt nergens aan natuurlijk.
> Ik wilde even zeggen dat de afvalwijzer niet meer op HACS te vinden is.

Is bekend. PR om 'm terug te krijgen in HACS staat nog open https://github.com/hacs/default/pull/611

**Comment by xirixiz** [comment]
Oke, I'm almost done with a new and working component without using the API but with all the same functionality.
I`ll release it Tomorrow or the day after Tomorrow

**Comment by Toinieboy** [comment]
``

> Oke, I'm almost done with a new and working component without using the API but with all the same functionality.
> I`ll release it Tomorrow or the day after Tomorrow

You are the best!

**Comment by xirixiz** [comment]
New release available (no API key required, same functionality!)

- Add scraper functionality (default now, no api key required)
- Make/keep the API functionality to be able to be configured
- Updated INFO, README

**Comment by Toinieboy** [comment]
You are the best! Also available through HACS?
